#!/bin/sh
set -e

MERGED_INDEX=""
for chart_dir in */; do
  [ -n "$(find "$chart_dir" -maxdepth 1 -name '*.tgz')" ] || continue
  if [ -n "$MERGED_INDEX" ]; then
    helm repo index "$chart_dir" --url "${CHART_BASE_URL}/${chart_dir}" --merge "$MERGED_INDEX"
  else
    helm repo index "$chart_dir" --url "${CHART_BASE_URL}/${chart_dir}"
  fi
  MERGED_INDEX="${chart_dir}index.yaml"
done

if [ -z "$MERGED_INDEX" ]; then
  echo "No packaged charts found - nothing to index"
  exit 0
fi

cp "$MERGED_INDEX" index.yaml
find . -mindepth 2 -name index.yaml -delete

{
  echo '<!-- This file is auto-generated by CI. Do not edit manually. -->'
  echo
  echo '# VAST Data Charts'
  echo
  echo 'Helm charts for VAST Data components.'
  echo
  echo '## Charts'
  echo
  for chart_dir in */; do
    [ -n "$(find "$chart_dir" -maxdepth 1 -name '*.tgz')" ] || continue
    echo "- [${chart_dir%/}](./${chart_dir%/})"
  done
  echo
  echo '## Usage'
  echo
  echo '```bash'
  echo "helm repo add vast-data https://${GITHUB_ORG}.github.io/${GITHUB_REPO}/"
  echo 'helm repo update'
  echo 'helm search repo vast-data'
  echo 'helm install my-release vast-data/<chart-name>'
  echo '```'
} > README.md

git add index.yaml README.md
if git diff --cached --quiet; then
  echo "No changes to publish"
  exit 0
fi

git config user.email "gitlab@vastdata.com"
git config user.name "gitlab-ci"
git commit -m "chore: update Helm repository index"
git remote set-url origin "https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
git push origin "HEAD:${CI_COMMIT_BRANCH}"
