#!/bin/sh
set -e

# Fail fast on a missing or malformed base URL: pushing an index full of
# malformed URLs is worse than a failed job.
: "${CHART_BASE_URL:?CHART_BASE_URL is not set}"
case "${CHART_BASE_URL#*://}" in
  *//*)
    echo "ERROR: CHART_BASE_URL contains empty path segments: ${CHART_BASE_URL}" >&2
    exit 1
    ;;
esac

# NOTE: index entry names come from the chart name inside each .tgz, not from
# the directory name. Renaming a directory only changes the download URLs.
MERGED_INDEX=""
for chart_dir in */; do
  [ -n "$(find "$chart_dir" -maxdepth 1 -name '*.tgz')" ] || continue
  if [ -n "$MERGED_INDEX" ]; then
    helm repo index "$chart_dir" --url "${CHART_BASE_URL}/${chart_dir}" --merge "$MERGED_INDEX"
  else
    helm repo index "$chart_dir" --url "${CHART_BASE_URL}/${chart_dir}"
  fi
  MERGED_INDEX="${chart_dir}index.yaml"
done

if [ -z "$MERGED_INDEX" ]; then
  echo "No packaged charts found - nothing to index"
  exit 0
fi

cp "$MERGED_INDEX" index.yaml
rm -f ./*/index.yaml

# helm repo index stamps a fresh `created` timestamp on every entry each run,
# so a plain diff always reports changes. Compare ignoring timestamp lines and
# keep the committed index when nothing real changed.
if git cat-file -e HEAD:index.yaml 2>/dev/null; then
  old_stripped=$(git show HEAD:index.yaml | grep -vE '^ *(created|generated):')
  new_stripped=$(grep -vE '^ *(created|generated):' index.yaml)
  if [ "$old_stripped" = "$new_stripped" ]; then
    git checkout -- index.yaml
  fi
fi

{
  echo '<!-- This file is auto-generated by CI. Do not edit manually. -->'
  echo
  echo '# VAST Data Charts'
  echo
  echo 'Helm charts for VAST Data components.'
  echo
  echo '## Charts'
  echo
  for chart_dir in */; do
    [ -n "$(find "$chart_dir" -maxdepth 1 -name '*.tgz')" ] || continue
    echo "- [${chart_dir%/}](./${chart_dir%/})"
  done
  echo
  echo '## Usage'
  echo
  echo '```bash'
  echo "helm repo add vast-data https://${GITHUB_ORG}.github.io/${GITHUB_REPO}/"
  echo 'helm repo update'
  echo 'helm search repo vast-data'
  echo 'helm install my-release vast-data/<chart-name>'
  echo '```'
} > README.md

git add index.yaml README.md
if git diff --cached --quiet; then
  echo "No changes to publish"
  exit 0
fi

git config user.email "gitlab@vastdata.com"
git config user.name "gitlab-ci"
git commit -m "chore: update Helm repository index"

# Keep the token out of the remote URL so it cannot leak into git error output.
git remote set-url origin "https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
git config credential.helper '!f() { echo "username=gitlab-ci-token"; echo "password=${GITLAB_TOKEN}"; }; f'

# Retry once behind a rebase in case something landed since the job cloned.
if ! git push origin "HEAD:${CI_COMMIT_BRANCH}"; then
  git fetch origin "${CI_COMMIT_BRANCH}"
  git rebase "origin/${CI_COMMIT_BRANCH}"
  git push origin "HEAD:${CI_COMMIT_BRANCH}"
fi
